import type { Metadata } from "next";
import { Header } from "@/src/shared/components/shared/header";
import { Container } from "@/src/shared/components/shared/containter";

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function CheckOutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <main className = "min-h-screen bg-[#F4F1EE]"  >
        <Container>
            <Header className="border-none" hasSearch={false} hasCart={false} />
                  {children}
        </Container>
      </main>

  );
}
